name: Release and Publish

on:
  push:
    tags:
      - 'v*'
    paths-ignore:
      - 'README.md'
      - 'docs/**'
      - '.gitignore'
      - 'LICENSE'

jobs:
  release:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm i

      - name: Run tests
        run: npm test

      - name: Build project
        run: npm run build

      - name: Get current version
        id: current_version
        run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

  
      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Notify success
        run: |
          echo "✅ Successfully released version ${{ steps.current_version.outputs.version }}"
          echo "📦 Package published to NPM"
          echo "🏷️ Git tag created: v${{ steps.current_version.outputs.version }}"
          echo "📋 GitHub release created"

      - name: Skip release notification
        if: steps.version_check.outputs.should_release == 'false'
        run: |
          echo "ℹ️ No new version detected, skipping release"
          echo "Current version ${{ steps.current_version.outputs.version }} already exists as a tag"